package com.lanou.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.lanou.bean.ContractBean;
import com.lanou.entity.Contract;
import com.lanou.entity.ContractHis;

@MapperScan
public interface ContractHisMapper {
	/**
	 * 查询合同历史
	 * 
	 * @return
	 */
	List<ContractBean> selectAll();

	/**
	 * 根据厂家，查询该厂家下所有的合同信息
	 * 
	 * @return
	 */
	List<ContractHis> selectByFactoryName(String factory_name);

	/**
	 * 求出总金额最大的合同信息
	 * 
	 * @return
	 */
	ContractHis selectContractHisByTotalAmount();

	/**
	 * 求出近三月以来，合同列表
	 * 
	 * @param CREATE_TIME
	 * @return
	 */
	List<ContractHis> selectContractHisByTime(@Param("CREATE_TIME") String CREATE_TIME);

	// 7：根据年份，合同列表
	List<ContractHis> selectAllByYear(@Param("CREATE_TIME") String CREATE_TIME);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_HIS_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int deleteByPrimaryKey(String CONTRACT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_HIS_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insert(ContractHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_HIS_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insertSelective(Contract record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_HIS_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	ContractHis selectByPrimaryKey(String CONTRACT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_HIS_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKeySelective(ContractHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_HIS_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKey(ContractHis record);
}