package com.lanou.mapper;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.lanou.bean.ContractBean;
import com.lanou.bean.FactoryRecord;
import com.lanou.bean.jOutProductBean;
import com.lanou.entity.Contract;

@MapperScan
public interface ContractMapper {
	/**
	 * 厂家销售记录
	 * 
	 * @return
	 */
	List<FactoryRecord> selectFactoryLog();

	/**
	 * 查询所有
	 * 
	 * @return
	 */
	List<ContractBean> selectAll(Map<String, Object> map);

	/**
	 * 查询总记录条数
	 * 
	 * @param map
	 * @return
	 */
	int selectPageCount();

	/**
	 * 根据id查询
	 * 
	 * @param ID
	 * @return
	 */
	Contract selectByID(@Param("contract_id") String contract_id);

	/**
	 * 出货表
	 * 
	 * @param shipTime
	 * @return
	 */
	List<jOutProductBean> selectjOutProductByst(@Param("shipTime") String shipTime);

	/**
	 * 修改状态
	 * 
	 * @param record
	 * @return
	 */
	int updateStateByControctId(Map<String, Object> map);
	// int updateStateByControctId(@Param("CONTRACT_ID") String CONTRACT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int deleteByPrimaryKey(String CONTRACT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insert(Contract record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insertSelective(Contract record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	Contract selectByPrimaryKey(String CONTRACT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKeySelective(Contract record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table CONTRACT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKey(Contract record);
}