package com.lanou.mapper;

import java.util.List;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.Export;

@MapperScan
public interface ExportMapper {
	/**
	 * 报运单列表
	 * 
	 * @return
	 */
	List<Export> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXPORT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int deleteByPrimaryKey(String EXPORT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXPORT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insert(Export record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXPORT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insertSelective(Export record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXPORT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	Export selectByPrimaryKey(String EXPORT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXPORT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKeySelective(Export record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXPORT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKey(Export record);
}