package com.lanou.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.ExtCproduct;
import com.lanou.entity.ExtCproductHis;

@MapperScan
public interface ExtCproductHisMapper {
	/**
	 * 根据货物历史id查询附件历史
	 * 
	 * @param contractProductId
	 * @return
	 */
	List<ExtCproductHis> selectExtHisByProductHisId(@Param("contractProductId") String contractProductId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_HIS_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int deleteByPrimaryKey(String EXT_CPRODUCT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_HIS_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insert(ExtCproduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_HIS_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insertSelective(ExtCproductHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_HIS_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	ExtCproductHis selectByPrimaryKey(String EXT_CPRODUCT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_HIS_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKeySelective(ExtCproductHis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_HIS_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKey(ExtCproductHis record);
}