package com.lanou.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.ExtCproduct;
import com.lanou.entity.ExtEproduct;

@MapperScan
public interface ExtCproductMapper {

	/**
	 * 根据货物id查询附件
	 * 
	 * @param contractProductId
	 * @return
	 */
	List<ExtCproduct> selectExtByProductId(@Param("contractProductId") String contractProductId);
	List<ExtCproduct> selectExtPro(String CONTRACT_PRODUCT_ID);
	/**
	 * 通过货物id删除附件
	 * 
	 * @return
	 */
	int deleteExtcproductByContractProductId();

	/**
	 * 查询所有附件
	 * 
	 * @return
	 */
	List<ExtCproduct> selectAll();

	/**
	 * 根据货物id删除附件
	 * 
	 * @return
	 */
	int deleteExt_CproductByContractProductId(@Param("contractProductId") String contractProductId);

	/**
	 * 根据附件id删除附件
	 * 
	 * @param EXT_CPRODUCT_ID
	 * @return
	 */
	int deleteByPrimaryKey(String EXT_CPRODUCT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insert(ExtCproduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insertSelective(ExtCproduct eproduct);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	ExtCproduct selectByPrimaryKey(String EXT_CPRODUCT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKeySelective(ExtCproduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EXT_CPRODUCT_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKey(ExtCproduct record);
}