package com.lanou.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.lanou.bean.LoginLogBean;
import com.lanou.entity.LoginLog;

@MapperScan
public interface LoginLogMapper {
	/**
	 * 
	 * 根据年份查询登录记录
	 * 
	 * @return
	 */
	List<LoginLogBean> selectLoginYearTime(@Param("yearTime") String yearTime);

	/**
	 * 
	 * 查询年份
	 * 
	 * @return
	 */
	List<LoginLogBean> selectLoginYear();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table LOGIN_LOG_P
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int deleteByPrimaryKey(String LOGIN_LOG_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table LOGIN_LOG_P
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insert(LoginLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table LOGIN_LOG_P
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insertSelective(LoginLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table LOGIN_LOG_P
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	LoginLog selectByPrimaryKey(String LOGIN_LOG_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table LOGIN_LOG_P
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKeySelective(LoginLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table LOGIN_LOG_P
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKey(LoginLog record);
}