package com.lanou.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.junit.runners.Parameterized.Parameter;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.beans.support.PagedListHolder;

import com.lanou.entity.PackingList;

@MapperScan
public interface PackingListMapper {
	/**
	 * pagelist显示页面 查询所有装箱单
	 * 
	 * @return
	 */
	List<PackingList> selectAll();

	/**
	 * 根据id查看装箱单
	 * 
	 * @param packingListId
	 * @return
	 */
	PackingList selectById(@Param("packingListId") String packingListId);

	/**
	 * 删除所有
	 * 
	 * @param id
	 * @return
	 */
	int deleteAll(@Param("ids") String[] id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PACKING_LIST_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int deleteByPrimaryKey(String PACKING_LIST_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PACKING_LIST_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insert(PackingList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PACKING_LIST_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int insertSelective(PackingList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PACKING_LIST_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	PackingList selectByPrimaryKey(String PACKING_LIST_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PACKING_LIST_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKeySelective(PackingList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table PACKING_LIST_C
	 *
	 * @mbg.generated Mon Jan 08 14:47:56 CST 2018
	 */
	int updateByPrimaryKey(PackingList record);
}