package com.lanou.mapper;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.ShippingOrder;
@MapperScan
public interface ShippingOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int deleteByPrimaryKey(String SHIPPING_ORDER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insert(ShippingOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insertSelective(ShippingOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    ShippingOrder selectByPrimaryKey(String SHIPPING_ORDER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKeySelective(ShippingOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKey(ShippingOrder record);
}