package com.lanou.mapper;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.SysCode;
@MapperScan
public interface SysCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODE_B
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int deleteByPrimaryKey(String SYS_CODE_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODE_B
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insert(SysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODE_B
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int insertSelective(SysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODE_B
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    SysCode selectByPrimaryKey(String SYS_CODE_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODE_B
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKeySelective(SysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODE_B
     *
     * @mbg.generated Mon Jan 08 14:47:56 CST 2018
     */
    int updateByPrimaryKey(SysCode record);
}